# Generated by Django 4.2.9 on 2024-01-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(default='asdfad', max_length=50),
            preserve_default=False,
        ),
    ]
