# Generated by Django 4.2.9 on 2024-01-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='akash@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
