# Generated by Django 4.2.9 on 2024-01-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='description',
            new_name='feedback',
        ),
    ]
